platform :ios, '9.0'

target 'QADemoTodayExtension' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QADemoTodayExtension

end

target 'QAMemo' do

  pod 'CocoaSecurity'
  pod 'MBProgressHUD', '~> 0.9.2'

end
